apiVersion: v1
kind: PersistentVolume
metadata:
  name: bpv1
spec:
  capacity:
    storage: 4Mi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt
